services:
  - type: web
    name: photostiller-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MAX_IMAGE_MB
        value: "10"
      - key: MAX_URLS_PER_MESSAGE
        value: "5"
